name: mofasgd
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy
  - tqdm
  - pyyaml
  - pip
  - pip:
    - --pre torch==2.7.0.dev20250310+cu118 --index-url https://download.pytorch.org/whl/nightly/cu118
  - pip:
    - huggingface-hub
    - transformers
    - bitsandbytes
    - safetensors
    - wandb
    - -e GaLore/ 