# Standard optimizer parameters
lr: 0.008
betas: [0.9, 0.95]
weight_decay: 0.0
eps: 0.00000001

# GaLore group parameters
group_params:
  rank: 32
  update_proj_gap: 75
  scale: 0.25
  proj_type: 'std'
cooldown_frac: 0.4
 