# Standard optimizer parameters
lr: 0.001
betas: [0.9, 0.95]
weight_decay: 0.0
eps: 1.0e-8

# GaLore group parameters
group_params:
  rank: 128
  update_proj_gap: 200
  scale: 0.25
  proj_type: 'std'
cooldown_frac: 0.4
 