# Base MFSGD parameters
lr: 0.05
rank: 32
beta: 0.95
eta1: 0.25
eta2: 0
use_current_projection: true
use_ones_for_nonzero_s: false 
eps: 0.0000000001  # Epsilon value for numerical stability in singular value handling
max_value: 5  # Maximum value for clipping reciprocal singular values

# Beta warmup parameters
warmup_steps: 300  # Number of steps for beta warmup
beta_start: 0.65   # Initial beta value at start of warmup
beta_end: 0.85     # Final beta value after warmup
nesterov: false    # Whether to use Nesterov momentum

# Learning rate schedule parameters
scheduler_name: 'original'  # Use original scheduler by default
cooldown_frac: 0.4  # Fraction of training spent cooling down the learning rate 